os: linux
dist: xenial
language: java
jdk:
- openjdk17

services:
- docker

cache:
  directories:
  - "$HOME/.m2"

env:
  global:
  - MAVEN_OPTS="--add-opens java.base/java.lang=ALL-UNNAMED"
  - BITCOINJ_TAG=0.16.13-LIB
  - TAG_VERSION=$(git tag --list --points-at $HEAD | grep -v "latest")

install:
- sudo apt-get -qq update
- sudo apt-get install -y protobuf-compiler

before_script:
- "./scripts/install-deps.sh"

script:
- mvn -f xyz.balzaclang.balzac.parent/ -U clean install

after_success:
- mvn -f xyz.balzaclang.balzac.lib/ jacoco:report coveralls:report -DrepoToken=$REPO_TOKEN
- docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 build -t balzaclang/balzac:${TAG_VERSION} .

notifications:
  email:
    recipients:
    - atzeinicola@gmail.com
    on_success: change
    on_failure: always

deploy:
- provider: releases
  prerelease: true
  api_key:
    secure: "R3eI8b+fTnjaowIuEUxXXw56IbrWlVTm6r+Ozwd1zZbSvCB34cF34ZT0PJgcrEjAtJ+QCon83Fq9tG1ufpvtrOOuxVCDUvHtmC/ACB5F1I9h3flp+uwEua4rhEForTsf3ZQ/55NUojJ5OoZgoNLakFK9oSOahjQ0wMxoxhRhVrC16mzf3I8vzLvzoefsA3EoX53b1xRrxRr6aG2caaMHIcwCxA9UrdJ51iS4rAxyrR2tw+4y/Np8RMUZmtNB9XPtqB68+dUitOcCEVaIR9KY6l8S8gnjLgNtpxx5RITW74kBTA74HVNEtduNy6Dfl9wep/tOeut22K8ebgbIHgftq7nJqZuwu9ECeDXYmXoeV1PvKwY74B/DXX+/Z9E42835u4ypO1MDnPYgP3qXHTrAp7oTeIXrv7lUUyCpPPVKRNqlkS1+UeLhHbexTyWEJHrITGMnQz8mMMMFuQyVlGJwEHVXHcR9mYumhrBCiRAg0phu2vWTSeW7mNnJn0mQ/6NKASp2v1S5VZYz9oLkXPx1Chk3FxInCY5UTZz0vrKsGnVBPsPiBI/Baj/4s5amqS4mregtZVaK4aHtef6NjckPO1cC0TcL6ohfkkQbupSLYbPv/LfK271XgXNZc8NfkUCkgKbyPJbw8mCGfO0wFIurn/TvKI4pYHkrrAmU7mQi+3w="
  file_glob: true
  file: xyz.balzaclang.balzac.web/target/balzac*.war
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk17
    repo: balzac-lang/balzac
- provider: script
  script: bash scripts/docker_push.sh
  on:
    tags: true
    jdk: openjdk17
    repo: balzac-lang/balzac

