language: java

cache:
  directories:
  - $HOME/.m2

env:
  - GRADLE_VERSION=4.4.1

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y protobuf-compiler

before_script:
  - gradle wrapper --gradle-version=$GRADLE_VERSION
  - ./scripts/install-deps.sh

script:
  - ls -l "xyz.balzaclang.balzac" | grep -e "xyz\.balzaclang\.balzac\.lib.*-bundled\.jar"
  - mvn -f xyz.balzaclang.balzac.parent/ clean install

after_success:
  - mvn -f xyz.balzaclang.balzac.lib/ jacoco:report coveralls:report -DrepoToken=$REPO_TOKEN

notifications:
  email:
    recipients:
      - atzeinicola@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
