os: linux
dist: xenial
language: java
jdk:
- openjdk11

services:
- docker

cache:
  directories:
  - "$HOME/.m2"

env:
  global:
  - GRADLE_VERSION=4.10.3
  - BITCOIND_CONNECTOR_TAG=v0.16.0
  - BITCOINJ_TAG=0.16.10-LIB
  - LATEST_VERSION=$(date +%Y%m%d_%s)_$(git log -n 1 --pretty=format:"%h")

install:
- sudo apt-get -qq update
- sudo apt-get install -y protobuf-compiler

before_script:
- gradle -version
- gradle wrapper --gradle-version=$GRADLE_VERSION
- "./scripts/install-deps.sh"

script:
- ls -l "xyz.balzaclang.balzac" | grep -e "xyz\.balzaclang\.balzac\.lib.*-bundled\.jar"
- mvn -f xyz.balzaclang.balzac.parent/ -U clean install

after_success:
- mvn -f xyz.balzaclang.balzac.lib/ jacoco:report coveralls:report -DrepoToken=$REPO_TOKEN
- docker build -f docker/Dockerfile-slim -t balzaclang/balzac:latest -t balzaclang/balzac:${LATEST_VERSION} .
- docker build -f docker/Dockerfile-slim.arm32v7 -t balzaclang/balzac-arm32v7:latest -t balzaclang/balzac-arm32v7:${LATEST_VERSION} .
- docker build -f docker/Dockerfile-slim.arm64v8 -t balzaclang/balzac-arm64v8:latest -t balzaclang/balzac-arm64v8:${LATEST_VERSION} .

notifications:
  email:
    recipients:
    - atzeinicola@gmail.com
    on_success: change
    on_failure: always

deploy:
- provider: releases
  prerelease: true
  token:
    secure: bq3K1AYmQnkhO8SN8ao/9iGPAqjQNWP+LVTB22a3e1Nyp+BZ9DxM4z2Jwbzdx5qEUon7IHQSyCRoxkKNueMjBLCf8//fs+kltswkWQf8X7BQxn+9nE12Yl+L6h6AcK8ccolG8XH1CfzO/4VYVVWDeaE0PTxdZyTgDqxAAo3M7mAtuA3la0qWOF+R9M/bNSwzLy5sDIgbPXpu9QltF55wIxL4Wfgf3gWFDgt5q056Jycht9lzJ/eRS0P84VYoO4nccZrbehVhVyS1xbQUI3UWbSvYlBjjULa9UvC3pvXcB0eKIxS8zyg0vYG6/hQApEJRGVgtwSIlRIDMfKcU7NqXPsHVoFaQ4grroDvGex7WIVa+S2QsZasEENeEDP4j8OICGXIb85ehLSTv7HxMcG/lPeDXdOGyPevweHcRE7tJmT1dfrEIRsUWK/rUKS82kDDIoNcVOKwHpt60JzO/UlRw5P9Xf3tC5iSDVrP+0CPMKlyAdb3EdBxTmTDcGlkkdRuw59D7d3IzPkhgq2t51kCicjeg+9lr4/6GbUqW/YhskRhfs1Pu7IFPYZhuaKKku9yMicYsLZCk3gO6QvlEIPkue0PdCr7e/kTTA+31f3ho/R9JugJDO6qnG0mv7GynQ0J0k0lpCuri0kAs/iDsAEZ9XOEs19heg3nN6lUXIICOR+s=
  file_glob: true
  file: xyz.balzaclang.balzac.web/target/balzac*.war
  cleanup: false
  on:
    tags: true
    jdk: openjdk11
    repo: balzac-lang/balzac
- provider: script
  script: bash scripts/docker_push.sh
  on:
    tags: true
    jdk: openjdk11
    repo: balzac-lang/balzac


