name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
    paths-ignore:
    - 'README.md'
  workflow_dispatch:
    inputs:
      tag:
        description: Tag the image
        type: string
        default: 'latest'

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Java 17 on ubuntu-latest
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: maven

    - name: Install BitcoinJ dependency
      env:
        BITCOINJ_TAG: 0.16.13-LIB
      run: |
        [[ "${BITCOINJ_TAG}" == "" ]] && (echo "BITCOINJ_TAG is not set" && exit 1)

        echo "Cleaning directory $PWD/bitcoinj"
        rm -rf $PWD/bitcoinj || (echo "Unable to delete dir $PWD/bitcoinj" && exit 1)

        echo "Cloning repo https://github.com/natzei/bitcoinj.git"
        git clone https://github.com/natzei/bitcoinj.git || (echo "Unable to clone https://github.com/natzei/bitcoinj.git" && exit 1)

        echo "Checking out tag $BITCOINJ_TAG"
        git -C $PWD/bitcoinj checkout $BITCOINJ_TAG || (echo "Unable to checkout branch $BITCOINJ_TAG" && exit 1)

        echo "Installing BitcoinJ $BITCOINJ_TAG"
        $PWD/bitcoinj/gradlew -p $PWD/bitcoinj publishToMavenLocal -x test || (echo "Unable to install bitcoinj" && exit 1)

        echo "Cleaning directory $PWD/bitcoinj"
        rm -rf $PWD/bitcoinj || (echo "Unable to delete dir $PWD/bitcoinj" && exit 1)

    - name: Build with Maven
      run: mvn -B -f xyz.balzaclang.balzac.parent/ -DwarName=balzac -U clean install

    - name: Upload war artifact
      uses: actions/upload-artifact@v3
      with:
        name: war-artifact
        path: xyz.balzaclang.balzac.web/target/balzac.war

    - name: Upload war artifact to Github Releases
      uses: fnkr/github-action-ghr@v1
      if: ${{ github.ref_type == 'tag' }}
      env:
        GHR_PATH: xyz.balzaclang.balzac.web/target/balzac.war
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Publish coverage metrics to Coveralls.io
    #   run: mvn -B -f xyz.balzaclang.balzac.lib/ jacoco:report coveralls:report -DrepoToken=${{ secrets.COVERALLS_REPO_TOKEN }}

  get-war-file:
    runs-on: ubuntu-latest
    name: Build multi-arch docker images
    needs: [build]

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Download war artifact
      uses: actions/download-artifact@v3
      with:
        name: war-artifact
  
  docker-build:
      name: Build multi-arch docker images
      needs: [get-war-file]
      uses: aiblockofficial/workflows/.github/workflows/build-multi-platform.yml@main
      with:
        REGISTRY: ${{ vars.REGISTRY }}
        REPOSITORY: ${{ vars.REPOSITORY }}
        TAG: ${{ inputs.tag || 'latest' }}
        BUILD_ARGS: |
          war=balzac.war